name: Rollback payment-auth to first commit

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get first commit
        id: first_commit
        run: echo "hash=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT

      - name: test_repo
        run: |
          ls -la
          pwd
      

      - name: Restore payment-auth from first commit
        run: |
          FILE="f2.txt"
          git checkout ${{ steps.first_commit.outputs.hash }} -- $FILE
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $FILE
          git commit -m "Rollback $FILE to initial commit"
          git push origin main
